language: node_js
node_js:
  - "14"
sudo: required
addons:
  chrome: stable
cache:
  yarn: true
env:
  global:
    - COVERALLS_PARALLEL=true
jobs:
  include:
    - name: format check
      script:
      - yarn prettier-check
      - yarn build-package
    - name: karma
      script:
      - export COVERALLS_FLAG_NAME=karma
      - mkdir dist
      - yarn build-icons
      - yarn build-less
      - yarn test-karma
      - cat coverage/chrome/karma.lcov | yarn coveralls
    - name: strict nyc
      script:
      - export NODE_ENV=TEST
      - export COVERALLS_FLAG_NAME=strict
      - yarn test-nyc | yarn coveralls
    - name: ticlo nyc
      script:
      - export COVERALLS_FLAG_NAME=ticlo
      - yarn ticlo-test-nyc | yarn coveralls

notifications:
  webhooks: https://coveralls.io/webhook
