name: Test

on:
  push:
    branches:
      - master
      - ghaction

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: enable corepack
        run: corepack enable
      - run: pnpm install
      - run: pnpm run prettier-check
  #      - run: pnpm run build-package

  test-browser:
    runs-on: ubuntu-latest
    steps:
      - uses: MathRobin/timezone-action@v1.1
        with:
          timezoneLinux: 'America/Los_Angeles'
      - name: enable corepack
        run: corepack enable
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 138
          install-chromedriver: true
      - uses: actions/checkout@v4
      - run: pnpm install
      - name: make dir
        run: |
          mkdir coverage
          mkdir css
      - run: pnpm run build-icons
      - run: pnpm run build-less
      - name: Vitest Browser Build Cache
        run: pnpm run test-browser-coverage
        continue-on-error: true
      - name: Vitest Browser
        run: pnpm run test-browser-coverage
      - name: Coveralls Vitest Browser
        uses: coverallsapp/github-action@v2
        env:
          NODE_COVERALLS_DEBUG: 1
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./coverage/browser/lcov.info
          parallel: true
          flag-name: browser
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: MathRobin/timezone-action@v1.1
        with:
          timezoneLinux: 'America/Los_Angeles'
      - uses: actions/checkout@v2
      - name: enable corepack
        run: corepack enable
      - run: pnpm install
      - name: make dir
        run: |
          mkdir coverage
          mkdir css
      - name: Vitest
        run: pnpm run test-coverage
      - name: Coveralls Vitest
        uses: coverallsapp/github-action@v2
        env:
          NODE_COVERALLS_DEBUG: 1
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./coverage/node/lcov.info
          parallel: true
          flag-name: strict
      #      - name: Test Node (Strict)
      #        run: pnpm run test-nyc-strict
      #      - name: Coveralls Node Strict
      #        uses: coverallsapp/github-action@v2
      #        env:
      #          NODE_COVERALLS_DEBUG: 1
      #        with:
      #          github-token: ${{ secrets.github_token }}
      #          path-to-lcov: ./coverage/nyc-strict.lcov
      #          parallel: true
      #          flag-name: strict
      - name: make coverage dir again
        run: mkdir coverage
      - name: Test Ticlo
        run: pnpm run ticlo-test-nyc
      - name: Coveralls Ticlo
        uses: coverallsapp/github-action@v2
        env:
          NODE_COVERALLS_DEBUG: 1
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./coverage/nyc-ticlo.lcov
          parallel: true
          flag-name: ticlo

  finish-coverage:
    needs: [test, test-browser]
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
